temp comment out checks so can debug codecov

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -160,52 +160,52 @@ jobs:
           sessioninfo::session_info(pkgs, include_base = TRUE)
         shell: Rscript {0}
 
-        # runs rmdcheck, first runs 'devtools::install to make sure there is a copy of mixOmics the parallel workers can access'
-      - name: Check ✅ 
-        if: (!contains(github.event.head_commit.message, 'skip-check'))
-        run: |
-          remotes::install_cran("devtools", Ncpus=2)
-          devtools::install()
-          devtools::check(args = c("--no-manual"), error_on = "warning", check_dir = "check")
-        shell: Rscript {0}
+      #   # runs rmdcheck, first runs 'devtools::install to make sure there is a copy of mixOmics the parallel workers can access'
+      # - name: Check ✅ 
+      #   if: (!contains(github.event.head_commit.message, 'skip-check'))
+      #   run: |
+      #     remotes::install_cran("devtools", Ncpus=2)
+      #     devtools::install()
+      #     devtools::check(args = c("--no-manual"), error_on = "warning", check_dir = "check")
+      #   shell: Rscript {0}
 
-      - name: BiocCheck 🧬 ✅
-        if: (!contains(github.event.head_commit.message, 'skip-check'))
-        run: |
-          BiocManager::install("BiocCheck", Ncpus=2)
-          BiocCheck::BiocCheck(".")
-        shell: Rscript {0}
+      # - name: BiocCheck 🧬 ✅
+      #   if: (!contains(github.event.head_commit.message, 'skip-check'))
+      #   run: |
+      #     BiocManager::install("BiocCheck", Ncpus=2)
+      #     BiocCheck::BiocCheck(".")
+      #   shell: Rscript {0}
 
-      - name: Check --as-cran ✅ ✅ 
-        if: (github.event_name == 'schedule' && github.repository == 'mixOmicsTeam/mixOmics') || (github.event_name == 'workflow_dispatch' && github.repository == 'mixOmicsTeam/mixOmics')
-        env:
-          _R_CHECK_CRAN_INCOMING_: false
-        run: |
-          options(devtools.check.dir = "check/asCRAN", devtools.check.warning = "never")
-          devtools::check(args = c("--no-manual", "--as-cran", "--ignore-vignettes", "--run-dontrun"), build_args = c("--no-build-vignettes"))
-        shell: Rscript {0}
+      # - name: Check --as-cran ✅ ✅ 
+      #   if: (github.event_name == 'schedule' && github.repository == 'mixOmicsTeam/mixOmics') || (github.event_name == 'workflow_dispatch' && github.repository == 'mixOmicsTeam/mixOmics')
+      #   env:
+      #     _R_CHECK_CRAN_INCOMING_: false
+      #   run: |
+      #     options(devtools.check.dir = "check/asCRAN", devtools.check.warning = "never")
+      #     devtools::check(args = c("--no-manual", "--as-cran", "--ignore-vignettes", "--run-dontrun"), build_args = c("--no-build-vignettes"))
+      #   shell: Rscript {0}
 
-      - name: Upload check results ⬆️
-        if: failure()
-        uses: actions/upload-artifact@master
-        with:
-          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
-          path: check
+      # - name: Upload check results ⬆️
+      #   if: failure()
+      #   uses: actions/upload-artifact@master
+      #   with:
+      #     name: ${{ runner.os }}-r${{ matrix.config.r }}-results
+      #     path: check
 
-      - name: Show testthat output 📖
-        if: always()
-        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
+      # - name: Show testthat output 📖
+      #   if: always()
+      #   run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+      #   shell: bash
 
-      - name: Push to DockerHub 📦
-        if: runner.os == 'Linux' && needs.versions.outputs.dockerise == 'true' && !contains(github.event.head_commit.message, 'skip-docker')
-        uses: docker/build-push-action@v1
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-          repository: mixomicsteam/mixomics
-          tags: ${{ needs.versions.outputs.docker_tag }}
-          build_args: BIOC_VERSION=${{ needs.versions.outputs.bioc }} 
+      # - name: Push to DockerHub 📦
+      #   if: runner.os == 'Linux' && needs.versions.outputs.dockerise == 'true' && !contains(github.event.head_commit.message, 'skip-docker')
+      #   uses: docker/build-push-action@v1
+      #   with:
+      #     username: ${{ secrets.DOCKER_USERNAME }}
+      #     password: ${{ secrets.DOCKER_PASSWORD }}
+      #     repository: mixomicsteam/mixomics
+      #     tags: ${{ needs.versions.outputs.docker_tag }}
+      #     build_args: BIOC_VERSION=${{ needs.versions.outputs.bioc }} 
 
       - name: Test coverage
         if: (runner.os == 'Linux' && github.event_name == 'schedule' && github.repository == 'mixOmicsTeam/mixOmics') || (runner.os == 'Linux' && github.event_name == 'workflow_dispatch' && github.repository == 'mixOmicsTeam/mixOmics')
